---
- hosts: all
  become: true
  roles:
    - dokku_bot.ansible_dokku
  vars:
    dokku_hostname: "{{ inventory_hostname }}"
    dokku_packages_state: latest
    dokku_vhost_enable: true
    dokku_mysql_db_name: "reims2-db"
    dokku_network_name: "reims2"
    dokku_users:
      - name: Github Actions
        username: ci-deploy
        ssh_key: "{{ lookup('file', 'creds/deploy_key.pub') }}"
      - name: Local developer for debug
        username: dev
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: mariadb
        url: https://github.com/dokku/dokku-mariadb.git
    aws_key_id: AKIAYEM6NADWH3DNKDFE
    aws_secret_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38613833363963336663666163333238316230353264326633393931623666643763306638373239
      6130626132353536623934336663363265396234363464650a356137346437653263326366376131
      65333566623039386265636461623566396439306137383934333937633564613565643865346233
      3835303464306665340a373534306234383037383364383030326362643230653664353435316263
      31333361306337656631363966663562363064346631663764396466386439363062666466616531
      3632623962663634393736366564656236663332303430646162
    aws_bucket_name: reims2-backup
    mysql_dump: "{{ lookup('file', 'dump.sql') }}"
  tasks:
    - name: dokku create api
      dokku_app:
        app: api
    - name: dokku create frontend
      dokku_app:
        app: frontend
    - name: dokku create docs
      dokku_app:
        app: docs

    - name: Create mysql
      dokku_service_create:
        name: "{{dokku_mysql_db_name}}"
        service: mariadb
    - name: Disable Mysql strict mode (to allow zero dates)
      blockinfile:
        path: "/var/lib/dokku/services/mariadb/{{dokku_mysql_db_name}}/config/disable_strict_mode.cnf"
        create: "yes"
        block: |
          [mysqld]
          sql_mode="ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION"
    - name: Restart mysql to apply config
      shell: "dokku mariadb:restart {{dokku_mysql_db_name}}"
    - name: Link database to api
      dokku_service_link:
        app: api
        name: "{{dokku_mysql_db_name}}"
        service: mariadb
    - name: Enable backups for mysql to S3
      shell: |
        dokku mariadb:backup-auth {{dokku_mysql_db_name}} {{aws_key_id}} {{aws_secret_key}}
        dokku mariadb:backup-schedule {{dokku_mysql_db_name}} "0 2,10,18 * * *" {{aws_bucket_name}}
    - name: Set multiple variables for frontend
      dokku_config:
        app: frontend
        config:
          DOKKU_LETSENCRYPT_EMAIL: substantialimpulse@pm.me
          PORT: "5000"
          API_URL: "http://api.web:5000/pvh/api"
          DOCS_URL: "http://docs.web:5000"
          HOST: "0.0.0.0"
    - name: Set letsencrypt mail and port for api
      dokku_config:
        app: api
        config:
          DOKKU_LETSENCRYPT_EMAIL: substantialimpulse@pm.me
          PORT: "5000"
    - name: Set host and port for docs
      dokku_config:
        app: docs
        config:
          PORT: "5000"
          HOST: "0.0.0.0"

    - name: Create network configuration (all apps in one network)
      shell: |
        dokku network:create {{dokku_network_name}}
        dokku network:set frontend attach-post-deploy {{dokku_network_name}}
        dokku network:set api attach-post-deploy {{dokku_network_name}}
        dokku network:set docs attach-post-deploy {{dokku_network_name}}
        dokku network:rebuildall

    - name: Deploy frontend from git (this takes up to 10 minutes)
      dokku_clone:
        app: frontend
        repository: https://github.com/reims2/reims2-frontend
        version: main
        build: True
    - name: Deploy api from git (this takes up to 5 minutes)
      dokku_clone:
        app: api
        repository: https://github.com/reims2/reims2-backend
        version: main
        build: True
    - name: Deploy docs from git (this takes up to 5 minutes)
      dokku_clone:
        app: docs
        repository: https://github.com/reims2/reims2-docs
        version: main
        build: True
    - name: Add main domain to frontend
      dokku_domains:
        app: frontend
        domains:
          - "{{ inventory_hostname }}"
    - name: Disable docs proxy
      dokku_proxy:
        app: docs
        state: absent
    - name: Enable frontend letsencrypt
      dokku_letsencrypt:
        app: frontend
    - name: Enable API letsencrypt
      dokku_letsencrypt:
        app: api
    - name: Enable letsencrypt auto renew
      shell: dokku letsencrypt:cron-job --add
    - name: Copy SQL dump file onto host
      tags: restore-mysql
      copy:
        content: "{{mysql_dump}}"
        dest: /tmp/reims-dump.sql
        mode: 0600
        owner: root
        group: root
        force: True
      when: mysql_dump != ""
    - name: Stop API for restoring dump
      tags: restore-mysql
      when: mysql_dump != ""
      command: "dokku ps:stop api"
    - name: Restore database from dump file
      tags: restore-mysql
      shell: "dokku mariadb:import {{dokku_mysql_db_name}} < /tmp/reims-dump.sql"
      when: mysql_dump != ""
    - name: Start API after dump restored
      tags: restore-mysql
      when: mysql_dump != ""
      command: "dokku ps:start api"
