---
roles:
  - name: jnv.unattended-upgrades
  - name: geerlingguy.swap
  - name: geerlingguy.docker

collections:
  - name: devsec.hardening
  - name: community.general
  - name: community.mysql
  - name: community.docker
