---
roles:
  - name: hifis.unattended_upgrades
    version: v3.1.0
  - name: geerlingguy.swap
    version: 1.0.2
  - name: geerlingguy.docker
    version: 6.1.0

collections:
  - name: devsec.hardening
    version: 8.6.0
  - name: community.general
    version: 7.1.0
  - name: community.mysql
    version: 3.7.2
  - name: community.docker
    version: 3.4.8
