---
roles:
  - name: hifis.unattended_upgrades
    version: v3.2.1
  - name: geerlingguy.swap
    version: 1.2.0
  - name: geerlingguy.docker
    version: 7.3.0

collections:
  - name: devsec.hardening
    version: 10.0.0
  - name: community.general
    version: 9.2.0
  - name: community.mysql
    version: 3.9.0
  - name: community.docker
    version: 3.11.0
