---
roles:
  - name: hifis.unattended_upgrades
    version: v3.2.1
  - name: geerlingguy.swap
    version: 1.2.0
  - name: geerlingguy.docker
    version: 7.4.1

collections:
  - name: devsec.hardening
    version: 9.0.1
  - name: community.general
    version: 9.4.0
  - name: community.mysql
    version: 3.10.2
  - name: community.docker
    version: 3.12.1
