---
roles:
  - name: hifis.unattended_upgrades
    version: v3.2.1
  - name: geerlingguy.swap
    version: 1.2.0
  - name: geerlingguy.docker
    version: 7.0.2

collections:
  - name: devsec.hardening
    version: 9.0.1
  - name: community.general
    version: 8.2.0
  - name: community.mysql
    version: 3.8.0
  - name: community.docker
    version: 3.5.0
