- name: Print debug and add SSH keys
  hosts: all
  tasks:
    - name: Print ip address
      debug: var=ansible_default_ipv4.address
    - name: Set authorized SSH pubkeys from file
      authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{ lookup('file', 'creds/pub_keys') }}"

- name: Enable auto upgrade, enable swap and some helpful packages
  hosts: all
  become: true
  roles:
    - geerlingguy.swap
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot_time: "06:00"
      unattended_update_days: '{ "Mon" }'
  vars:
    swap_file_size_mb: "2048" # some swap for more RAM during Dokku deploys
  tasks:
    - name: Apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install some packages (user-specified)
      ansible.builtin.package:
        name:
          - htop
          - nano
          - libpam-systemd # ssh session closed after reboot
        state: present

- name: OS hardening
  hosts: all
  become: true
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    os_auth_pw_max_age: 99999 # nobody wants to be forced to change PW
    os_auth_pw_min_age: 0
    os_auth_allow_homeless: true
    os_env_umask: "022"
    os_selinux_state: disabled
    os_auditd_enabled: false # lxd container
    os_auth_pam_passwdqc_enable: false # dont need strong PW policy
    ssh_permit_root_login: "yes"
    sftp_enabled: true
    ssh_print_motd: true
    ssh_print_pam_motd: true
    ssh_max_auth_retries: 4
    sftp_umask: "0022"
    os_ignore_home_folder_users: [dokku]
  collections:
    - devsec.hardening
  roles:
    - os_hardening
    - ssh_hardening
  post_tasks:
    - name: Reboot to apply sysctl params
      reboot:

- name: Configure ufw
  hosts: all
  become: true
  tasks:
    - name: Allow ssh
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: Allow http
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow https
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
