---
- name: Copy SQL dump file onto host
  ansible.builtin.copy:
    content: "{{ db_dump }}"
    dest: /tmp/reims-dump.sql
    mode: 0600
    owner: root
    group: root
    force: true

- name: Stop API for restoring dump
  ansible.builtin.command: "dokku ps:stop {{ api_app_name }}"

- name: Restore database from dump file
  ansible.builtin.shell: "dokku mariadb:import {{ db_name }} < /tmp/reims-dump.sql"

- name: Start API after dump restored
  ansible.builtin.command: "dokku ps:start {{ api_app_name }}"
