---
- name: Copy SQL dump file onto host
  copy:
    content: "{{db_dump}}"
    dest: /tmp/reims-dump.sql
    mode: 0600
    owner: root
    group: root
    force: True

- name: Stop API for restoring dump
  command: "dokku ps:stop {{api_app_name}}"

- name: Restore database from dump file
  shell: "dokku mariadb:import {{db_name}} < /tmp/reims-dump.sql"

- name: Start API after dump restored
  command: "dokku ps:start {{api_app_name}}"
