---
- name: Load docker-compose template
  set_fact:
      template_partial: "{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Add compose to stack
  blockinfile:
      dest: "{{ stack_file }}"
      content: "{{ template_partial }}"
      state: present
      validate: docker-compose -f %s config -q
      marker: "# {mark} ANSIBLE MANAGED BLOCK for frontend"
      insertafter: "services:"
  notify: reload stack
