version: "3"
services:
  proxy:
    image: docker.io/library/traefik:v2.10.1
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
 
    read_only: true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"


    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

    volumes:
      - "./dynamic_conf:/etc/traefik/dynamic_conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme:/etc/traefik/acme"

    command:
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entryPoints.traefik.address=:8080"
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=reims2"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.email=letsencrypt@kxlion.de"
      - "--certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entrypoint=http"

    networks:
      reims2:
  frontend:
    image: docker.io/reims2/reims2-frontend:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=http"
      - "traefik.http.routers.frontend.middlewares=compress"
    environment:
      - "BASE_URL_BROWSER=http://localhost"
      - "BASE_URL_INTERNAL=http://backend:5000"
    networks:
      reims2:
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  backend:
    image: docker.io/reims2/reims2-backend:latest
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=http"
      - "traefik.http.routers.backend.middlewares=compress"
    environment:
      - "PVH_JWT_SECRET=dsndkjnakdjnasasdnasdkjwnqdjnqdnassjdaksjdnkajnsdkjnaskdjnaksjndkajsndknwkjdnqkjwndkqwdoqsdiwjeodejqwodjoj"
      - "PVH_DEBUG=true"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=3306"
      - "DATABASE_NAME=reims2-db"
      - "DATABASE_USER=reims2"
      - "DATABASE_PASSWORD=reims2"
    networks:
      reims2:
      db:
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
 
  docs:
    image: docker.io/reims2/reims2-docs:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`localhost`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.docs.entrypoints=http"
      - "traefik.http.routers.docs.middlewares=compress"
    networks:
      reims2:
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
 

  db:
    image: docker.io/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "reims2-db"
      MARIADB_USER: "reims2"
      MARIADB_PASSWORD: "reims2"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/reims2-db.sql
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      db:
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
 

networks:
  reims2:
    name: reims2
  db:
