- name: Install packages
  ansible.builtin.package:
    name:
      - prometheus
    state: present

- name: Create install directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "root"
    group: "root"
  with_items:
    - "{{ grafana_install_location }}"
  become: true
  tags:
    - grafana

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "root"
    group: "root"
  with_items:
    - "{{ grafana_data_location }}"
  become: true
  tags:
    - grafana

- name: Load docker-compose template
  ansible.builtin.set_fact:
    template_partial: "{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Add compose to stack
  ansible.builtin.blockinfile:
    dest: "{{ stack_file }}"
    content: "{{ template_partial }}"
    state: present
    validate: docker-compose -f %s config -q
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{role_name}}"
    insertafter: "services:"
  notify: reload stack

- name: Copy prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload prometheus
# - name: Expose DB tasks
#   ansible.builtin.include_tasks: expose_db.yml
#   vars:
#     port: "{{ item.port }}"
#     db_name: "{{ item.name }}"
#   loop: "{{ db_port_mapping }}"
