- name: Install packages
  ansible.builtin.package:
    name:
      - prometheus
    state: present

- name: Create install directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "root"
    group: "root"
  with_items:
    - "{{ grafana_install_location }}"
  become: true
  tags:
    - grafana

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "root"
    group: "root"
    setype: "container_file_t"
  with_items:
    - "{{ grafana_data_location }}"
  become: true
  tags:
    - grafana

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_install_location }}/docker-compose.yml"
    mode: "0600"
    owner: "root"
    group: "root"
    validate: docker-compose -f %s config -q
  tags:
    - docker
    - grafana
  become: true

- name: Compose grafana
  community.docker.docker_compose:
    state: present
    project_src: "{{ grafana_install_location }}"
    pull: true
    remove_orphans: true
  tags:
    - grafana
  become: true

- name: Copy prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload prometheus

- name: Expose DB tasks
  ansible.builtin.include_tasks: expose_db.yml
  vars:
    port: "{{ item.port }}"
    db_name: "{{ item.name }}"
  loop: "{{ db_port_mapping }}"
