---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
    owner: "root"
    group: "docker"
  with_items:
    - "{{ backend_db_location }}"
  become: true

- name: Load docker-compose template
  ansible.builtin.set_fact:
    template_partial: "{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Add compose to stack
  ansible.builtin.blockinfile:
    dest: "{{ stack_file }}"
    content: "{{ template_partial }}"
    state: present
    validate: docker-compose -f %s config -q
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{role_name}}"
    insertafter: "services:"
  notify:
    - reload stack
    - wait for mariadb
    - restore dump

- name: Copy SQL dump file onto host
  ansible.builtin.copy:
    content: "{{ db_dump }}"
    dest: /tmp/reims-dump.sql
    mode: "0600"
    owner: root
    group: root
    force: true
