---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
    owner: "root"
    group: "docker"
  with_items:
    - "{{ backend_db_location }}"
  become: true

- name: Load docker-compose template
  ansible.builtin.set_fact:
    template_partial: "{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Add compose to stack
  ansible.builtin.blockinfile:
    dest: "{{ stack_file }}"
    content: "{{ template_partial }}"
    state: present
    validate: docker-compose -f %s config -q
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{role_name}}"
    insertafter: "services:"
  notify:
    - reload stack
    - wait for mariadb

- name: Copy SQL dump file onto host
  ansible.builtin.copy:
    content: "{{ db_dump }}"
    dest: "{{ dump_location }}"
    mode: "0600"
    owner: root
    group: root
    force: true
  register: dump_file
  when: db_dump is not false

- name: Flush handlers to make restoring dump possible
  ansible.builtin.meta: flush_handlers
  when: db_dump is not false

- name: Restore dump
  args:
    executable: /bin/bash
  shell: |
    set -o pipefail
    cat {{ dump_location }} | docker exec -i $(docker ps -q -f name={{ stack_name }}_mariadb) /usr/bin/mariadb -p{{ reims2_db_root_password }} {{ reims2_db_name }}
  when: db_dump is not false
