- name: Set authorized SSH pubkeys from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'creds/pub_keys') }}"

- name: Enable auto upgrade
  ansible.builtin.include_role:
    name: jnv.unattended-upgrades
  vars:
    unattended_automatic_reboot_time: "06:00"
    unattended_update_days: '{"Mon"}'
    unattended_download_upgradeable: 7

- name: Enable swap
  ansible.builtin.include_role:
    name: geerlingguy.swap
  vars:
    swap_file_size_mb: "2048" # some swap for more RAM during Dokku deploys

- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Install some packages (user-specified)
  ansible.builtin.package:
    name:
      - htop
      - nano
      - goaccess
      - libpam-systemd # ssh session closed after reboot
    state: present

- name: Allow ssh ufw
  community.general.ufw:
    rule: allow
    name: OpenSSH
- name: Allow http ufw
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp
- name: Allow https ufw
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp
- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
