name: deploy

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Release new version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@00765f79cffbf77b8bef397c00d492d8241502be # v2
        with:
          playbook: main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          options: |
            --inventory hosts
